version: "3"
services:
  web:
    build: ./ui/
    links:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./web:/code
  api:
    build: ./api/
    ports:
      - "5000:5000"
    links:
      - redis
    volumes:
      - ./api:/code
  redis:
      image: "redis:alpine"
