version: "3"
services:
  web:
    build: ./ui/
    ports:
      - "3000:3000"
    volumes:
      - ./web:/code
    depends_on:
      - api
  api:
    build: ./api/
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./api:/code
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
